# Generated by Django 2.2.1 on 2019-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('SR', 'Super Rare'), ('UR', 'Ultra Rare'), ('ULT_RARE', 'Ultimate Rare'), ('GR', 'Ghost Rare'), ('GUR', 'Gold Ultra Rare')], max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('card_type', models.CharField(choices=[('NORMAL', 'Normal'), ('CONTINUOUS', 'Continuous'), ('EQUIP', 'Equip'), ('QUICK_PLAY', 'Quick-play'), ('FIELD', 'Field'), ('RITUAL', 'Ritual')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('SR', 'Super Rare'), ('UR', 'Ultra Rare'), ('ULT_RARE', 'Ultimate Rare'), ('GR', 'Ghost Rare'), ('GUR', 'Gold Ultra Rare')], max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('atk_pts', models.IntegerField(default=0)),
                ('def_pts', models.IntegerField(default=0)),
                ('attribute', models.CharField(choices=[('DARK', 'Dark'), ('DIVINE', 'Divine'), ('EARTH', 'Earth'), ('FIRE', 'Fire'), ('LIGHT', 'Light'), ('WATER', 'Water'), ('WIND', 'Wind')], max_length=30)),
                ('card_type', models.CharField(choices=[('NORMAL', 'Normal'), ('EFFECT', 'Effect'), ('RITUAL', 'Ritual'), ('FUSION', 'Fusion'), ('SYNCHRO', 'Synchro'), ('XYZ', 'XYZ')], max_length=30)),
                ('monster_type', models.CharField(choices=[('AQUA', 'Aqua'), ('BEAST', 'Beast'), ('BEAST_WARRIOR', 'Beast-Warrior'), ('DINOSAUR', 'Dinosaur'), ('DRAGON', 'Dragon'), ('FAIRY', 'Fairy'), ('FIEND', 'Fiend'), ('FISH', 'Fish'), ('INSECT', 'Insect'), ('MACHINE', 'Machine'), ('PLANT', 'Plant'), ('PSYCHIC', 'Psychic'), ('PYRO', 'Pyro'), ('REPTILE', 'Reptile'), ('ROCK', 'Rock'), ('SEA_SERPENT', 'Sea Serpent'), ('SPELLCASTER', 'Spellcaster'), ('THUNDER', 'Thunder'), ('WARRIOR', 'Warrior'), ('WINGED_BEAST', 'Winged Beast'), ('WYRM', 'Wyrm'), ('ZOMBIE', 'Zombie')], max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('effect', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('SR', 'Super Rare'), ('UR', 'Ultra Rare'), ('ULT_RARE', 'Ultimate Rare'), ('GR', 'Ghost Rare'), ('GUR', 'Gold Ultra Rare')], max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('card_type', models.CharField(choices=[('NORMAL', 'Normal'), ('CONTINUOUS', 'Continuous'), ('COUNTER', 'Counter')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
